### ISSUE TITLE
runing your code on gpu

### ISSUE THREAD

**Issue by xerxes-y** [RandolphVI/Next-Basket-Recommendation#1]
hi i read your code and need too run on gpu but your model in train just working on cpu can you change 
torch.mm(du_latest, item_embedding[negtives].t()).data.numpy()[0]

**Comment by RandolphVI** [comment]
Hi @khshayarr ,

Sorry to reply so late (a little busy recently), what you mentioned about, running the code on the GPU, it seems that you can turn the vars into .cuda() type based on PyTorch.

Hope this helps!
